text<-grep("^2/2/2007;|^1/2/2007;",readLines("household_power_consumption.txt"),value = TRUE)
header<-readLines("household_power_consumption.txt",n=1)
header<-unlist(strsplit(header,split=";"))
mydata<-read.table(textConnection(text),sep=";",na.strings = "?")
colnames(mydata)<-header
mydata$Time<-paste(mydata$Date,mydata$Time)
mydata$Time<-as.POSIXct(mydata$Time,format="%d/%m/%Y %H:%M:%S")
png("plot2.png", width=480, height=480)
plot(mydata$Time,mydata$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (Kilowatts)")
dev.off()