text<-grep("^2/2/2007;|^1/2/2007;",readLines("household_power_consumption.txt"),value = TRUE)
header<-readLines("household_power_consumption.txt",n=1)
header<-unlist(strsplit(header,split=";"))
mydata<-read.table(textConnection(text),sep=";")
colnames(mydata)<-header
mydata$Time<-paste(mydata$Date,mydata$Time)
mydata$Time<-as.POSIXct(mydata$Time,format="%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(mydata$Time,mydata$Sub_metering_1,type="l",xlab = "",ylab = "Energy sub metering")
points(mydata$Time,mydata$Sub_metering_2,type="l",col="red")
points(mydata$Time,mydata$Sub_metering_3,type="l",col="blue")
legend("topright",legend = c("sub_metering_1","sub_metering_2","sub_metering_3"),col = c("black","red","blue"),lty = 1,cex=0.75,bg=NA)
dev.off()